# Generated by Django 5.2.10 on 2026-01-10 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_chatmessage_session_id_chatmessage_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('last_mentioned', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HierarchicalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('level', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=20)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeTriple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('object_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_object', to='api.entity')),
                ('source_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.chatmessage')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_subject', to='api.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
